version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: creditjambo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: creditjambo_client
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - creditjambo-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: creditjambo-backend
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/creditjambo_client?schema=public
      PORT: 3001
      NODE_ENV: production
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 15m
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-this-in-production
      JWT_REFRESH_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000,http://localhost:3003
      THROTTLE_TTL: 60
      THROTTLE_LIMIT: 10
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - creditjambo-network
    restart: unless-stopped
    command: sh -c "pnpm prisma:migrate && pnpm seed && node dist/src/main.js"

  # Client Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: creditjambo-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - creditjambo-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  creditjambo-network:
    driver: bridge

